Bootstrap: docker
From: rockylinux/rockylinux:9

# missing: lua-bitop lua-json lua-lpeg lua-term exa fish
# unnecessary: tar less libstdc++ glibc bash

%post
  # Install necessary dependencies
  dnf install -y dnf-plugins-core
  dnf config-manager --set-enabled crb
  dnf install -y epel-release
  dnf install -y --nobest gcc make lua lua-devel lua-libs lua-posix 
    tcl tcl-devel wget curl openssh-clients ca-certificates zsh gzip bzip2 xz \
    luarocks.noarch
  luarocks install luabitop-53plus luaterminal lpeg lua-json
  # Install Lmod
  cd /tmp
  wget https://github.com/TACC/Lmod/archive/refs/tags/8.7.37.tar.gz
  tar xf 8.7.37.tar.gz
  cd Lmod-8.7.37
  ./configure --prefix=/opt/lmod
  make install
  cd /tmp
  rm -rf 8.7.37.tar.gz Lmod-8.7.37
  # Install Conda
  cd /tmp
  wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh" && \
  bash Miniforge3.sh -b -p /opt/conda && \
  rm Miniforge3.sh && \
  echo "done"
  # Set default shell to bash
  chsh -s /bin/bash

%files
    rocky/start_code.sh /opt/start_code.sh

%environment
    export S_CONDAENV=${S_CONDAENV:-$CONDA_DEFAULT_ENV}
    [[ -z "$http_proxy" ]] || export http_proxy=$http_proxy
    [[ -z "$https_proxy" ]] || export https_proxy=$https_proxy
    [[ -z "$no_proxy" ]] || export no_proxy=$no_proxy
    [[ -z "$ftp_proxy" ]] || export ftp_proxy=$ftp_proxy
    [[ -z "$all_proxy" ]] || export all_proxy=$all_proxy
    [[ -z "$rsync_proxy" ]] || export rsync_proxy=$rsync_proxy

%apprun code
    bash /opt/start_code.sh "${@}"

%apprun bash
    #!/bin/bash
    . /opt/conda/etc/profile.d/conda.sh && \
    . /opt/conda/etc/profile.d/mamba.sh && \
    alias ll='ls -l' && \
    echo "activating env $RS_CONDAENV" && \
    conda activate $RS_CONDAENV && \
    echo "starting BASH" && \
    /bin/bash

%runscript
    #!/bin/bash
    bash /opt/start_code.sh "${@}"


