Bootstrap: docker
From: rocker/rstudio

#%files
    #condarc /etc/conda/condarc

%post
    echo "lock-type=linkbased" > /etc/rstudio/file-locks
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p /opt/conda
    . /opt/conda/etc/profile.d/conda.sh
    conda install -c conda-forge -y mamba

%environment
    export CONDA_PREFIX=$RSTUDIO_CONDA_PREFIX
	export RSTUDIO_WHICH_R=$RSTUDIO_R_BIN
	export RETICULATE_PYTHON=$RSTUDIO_PY_BIN
	export PASSWORD=$RSTUDIO_PASSWORD
	export PORT=$RSTUDIO_PORT
	export USER=$USER

%apprun rserver
    echo "enabling conda" && \
      . /opt/conda/etc/profile.d/conda.sh && \
      . /opt/conda/etc/profile.d/mamba.sh && \
      echo "activating env $CONDA_PREFIX" && \
      conda activate $CONDA_PREFIX && \
      echo "starting RStudio Server" && \
      exec rserver "${@}"

%runscript
    echo "enabling conda" && \
      . /opt/conda/etc/profile.d/conda.sh && \
      . /opt/conda/etc/profile.d/mamba.sh && \
      echo "activating env $CONDA_PREFIX" && \
      conda activate $CONDA_PREFIX && \
      echo "starting RStudio Server" && \
      exec rserver "${@}"


