Bootstrap: docker
From: rocker/rstudio:4.1.3

%post
    echo "lock-type=linkbased" > /etc/rstudio/file-locks
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p /opt/conda
    . /opt/conda/etc/profile.d/conda.sh
    conda install -c conda-forge -y mamba

%environment
    export CONDA_PREFIX=${RS_CONDAENV:-$CONDA_DEFAULT_ENV}

%apprun rserver
    echo "enabling conda" && \
      . /opt/conda/etc/profile.d/conda.sh && \
      . /opt/conda/etc/profile.d/mamba.sh && \
      echo "activating env $CONDA_PREFIX" && \
      conda activate $CONDA_PREFIX && \
      echo "starting RStudio Server" && \
      exec rserver "${@}"

%runscript
    echo "starting RStudio Server" && \
      exec rserver "${@}"


