Bootstrap: docker
From: rockylinux/rockylinux:8

# perl-CPAN cpan install LSF::Base LSF::Batch

%post
  # Install necessary dependencies
  # libxcrypt-compat instead of libxcrypt in Rocky 9
  # compat-openssl10 not available in Rocky 9
  # fish not available in Rocky 8
  dnf install -y --allowerasing \
    dnf-plugins-core wget curl openssh-clients zsh gzip bzip2 xz git which \
    libnsl libxcrypt compat-openssl10 acl epel-release git diffutils iputils \
    zip unzip traceroute bind-utils net-tools procps-ng lsof
  ## Rocky 9 only ##
  # dnf config-manager --set-enabled crb
  # /bin/crb enable
  ## end Rocky 9 only ##
  dnf install -y Lmod lua-devel

  ## Rocky 8 only ##
  wget -O fish.rpm https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_8/x86_64/fish-3.7.1-3.1.x86_64.rpm
  dnf install -y fish.rpm
  rm -f fish.rpm
  ## end Rocky 8 only ##

  # Install exa
  mkdir inst_exa
  cd inst_exa
  wget -O exa.zip https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip
  unzip exa.zip
  mv bin/exa /usr/local/bin
  mv completions/exa.bash /etc/bash_completion.d/exa
  mv completions/exa.zsh /usr/share/zsh/site-functions/exa
  mkdir -p /usr/share/fish/vendor_completions.d/
  mv completions/exa.fish /usr/share/fish/vendor_completions.d/
  mv man/exa.1 /usr/share/man/man1/
  mv man/exa_colors.5 /usr/share/man/man5/
  cd ..
  rm -rf inst_exa

  # Install Conda
  
  wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh" && \
  bash Miniforge3.sh -b -p /opt/conda && \
  rm Miniforge3.sh && \
  echo "done"

%files
    vscode_rocky/start_code.sh /opt/start_code.sh

%environment
    export S_CONDAENV=${S_CONDAENV:-$CONDA_DEFAULT_ENV}
    [[ -z "$http_proxy" ]] || export http_proxy=$http_proxy
    [[ -z "$https_proxy" ]] || export https_proxy=$https_proxy
    [[ -z "$no_proxy" ]] || export no_proxy=$no_proxy
    [[ -z "$ftp_proxy" ]] || export ftp_proxy=$ftp_proxy
    [[ -z "$all_proxy" ]] || export all_proxy=$all_proxy
    [[ -z "$rsync_proxy" ]] || export rsync_proxy=$rsync_proxy

%apprun code
    bash /opt/start_code.sh "${@}"

%apprun bash
    #!/bin/bash
    . /opt/conda/etc/profile.d/conda.sh && \
    . /opt/conda/etc/profile.d/mamba.sh && \
    alias ll='ls -l' && \
    echo "activating env $RS_CONDAENV" && \
    conda activate $RS_CONDAENV && \
    echo "starting BASH" && \
    /bin/bash

%runscript
    #!/bin/bash
    bash /opt/start_code.sh "${@}"
