name: Singularity Build (native)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

  release:
    types: [created]

jobs:
  recipes:
    name: "Find Singularity recipes"
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.ff.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find recipe files (json output)
        id: ff
        run: |
          echo "::set-output name=files::$(
            find . -name "*Singularity*" |
            xargs -d \\n printf \"%s\", |
            sed -e 's/^/[/' -e 's/,$/]/'
          )"
      - name: Print files
        run: echo "${{ steps.ff.outputs.files }}"

  changes:
    name: "Changed Singularity Recipes"
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.format.outputs.files }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'
      - name: Print files
        run: echo "${{ steps.files.outputs.added_modified }}"
      - name: Keep only singularity recipes
        id: filter
        uses: edwardgeorge/jq-action@main
        with:
          input: ${{ steps.files.outputs.added_modified }}
          script: '[.[] | select(test("Singularity"))]'
      - name: Format recipes
        id: format
        run: |
          remove_newlines() {
            tr -d "\n" <<< '${{ steps.filter.outputs.output }}' | \
              sed 's/^\[ /['
          }
          echo "::set-output name=files::"$(remove_newlines)
      - name: Print
        run: echo ${{ steps.format.outputs.files }}
  
  select_filelist:
    needs: [recipes, changes]
    if: ${{ needs.changes.result == 'success' ||
            github.event_name == 'release' }}
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.select.outputs.files }}
    steps:
      - name: Select recipe list
        id: select
        run: |
          if ${{ github.event_name == 'release' }}; then
            echo '::set-output name=files::${{ needs.recipes.outputs.changed_file }}'
          else
            echo '::set-output name=files::${{ needs.changes.outputs.changed_file }}'
          fi
      - name: Print
        run: echo ${{ steps.select.outputs.files }}