name: Singularity Build (native)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

  release:
    types: [created]

jobs:
  recipes:
    name: "Find Singularity recipes"
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.ff.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find recipe files
        uses: jeertmans/filesfinder@v0.3.1-rc.2
        id: ff
        with:
          # Only argument, a single string, to be passed as arguments to ff.
          # See `ff --help` for more help.
          # Default: "*"
          args: "*Singularity*"
      - name: Print files
        run: echo "${{ steps.ff.outputs.files }}"
      - name: Find recipe files 2
        id: ff2
        uses: DovnarAlexander/github-action-file-detection@master
        with:
          wildcard: '*Singularity*'
          exit_code_found: 0
      - name: Print files 2
        run: echo "${{ steps.ff2.outputs.found }}"

  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'
      - name: Print files
        run: echo "${{ steps.files.outputs.added_modified }}"
  