name: Singularity Build (native)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

  release:
    types: [created]

jobs:
  recipes:
    name: "Find Singularity recipes"
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.ff.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find recipe files
        id: ff
        uses: DovnarAlexander/github-action-file-detection@master
        with:
          wildcard: '*Singularity*'
          exit_code_found: 0
      - name: Print files
        run: echo "${{ steps.ff.outputs.found }}"

  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'
      - name: Print files
        run: echo "${{ steps.files.outputs.added_modified }}"
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "repo_files_modified.json"
          json: ${{ steps.files.outputs.added_modified }}
      - name: Keep only singularity recipes
        id: filter
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq '.[] | select(test("Singularity"))' repo_files_modified.json
          multiline: true
      - name: Print rules
        run: echo "${{ steps.filter.outputs.value }}"
  